name: AWS Setup
description: Sets up AWS CLI and logs into AWS ECR

inputs:
  aws_account_id:
    description: 'AWS Account ID'
    required: true
    type: string
  aws_region:
    description: 'AWS Region'
    required: true
    type: string
  docker_registry:
    description: 'Docker Registry URL'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set Up AWS CLI
      run: |
        apt-get update
        apt-get install -y awscli
    - name: Docker Login to AWS
      run: |
        echo "Account: ${{ inputs.aws_account_id }}"
        echo "Region: ${{ inputs.aws_region }}"
        echo "Registry: ${{ inputs.docker_registry }}"
        aws ecr get-login-password --region "${{ inputs.aws_region }}" | docker login --username AWS --password-stdin "${{ inputs.docker_registry }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}